stages:
  # - test
  - deploy


deploy1:
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh-client

    - sshpass -p $PICAM1_PW scp -o StrictHostKeyChecking=no -r ./* $PICAM1_IP:$DEPLOY_PATH
    # Activate the virtual environment and restart the Flask application on port 9095
    # - sshpass -p $PICAM1_PW ssh -o StrictHostKeyChecking=no $PICAM1_IP "cd $DEPLOY_PATH && pip install -r requirements.txt"
    - sshpass -p $PICAM1_PW ssh -o StrictHostKeyChecking=no $PICAM1_IP "sudo systemctl restart picam2-streaming.service"

  only:
    - main  # Deploy only when changes are pushed to the main branch

deploy2:
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh-client
    # - echo $FILE_SERVICE_IP:$DEPLOY_PATH
    # Deploy to your server
    - sshpass -p $PICAM2_PW scp -o StrictHostKeyChecking=no -r ./* $PICAM2_IP:$DEPLOY_PATH
    # Activate the virtual environment and restart the Flask application on port 9095
    # - sshpass -p $PICAM2_PW ssh -o StrictHostKeyChecking=no $PICAM2_IP "cd $DEPLOY_PATH && pip install --break-system-packages -r requirements.txt"
    - sshpass -p $PICAM2_PW ssh -o StrictHostKeyChecking=no $PICAM2_IP "sudo systemctl restart picam2-streaming.service"

  only:
    - main  # Deploy only when changes are pushed to the main branch

deploy3:
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh-client
    # - echo $FILE_SERVICE_IP:$DEPLOY_PATH
    # Deploy to your server
    - sshpass -p $PICAM3_PW scp -o StrictHostKeyChecking=no -r ./* $PICAM3_IP:$DEPLOY_PATH
    - sshpass -p $PICAM3_PW ssh -o StrictHostKeyChecking=no $PICAM3_IP "sudo systemctl restart picam2-streaming.service"

  only:
    - main  # Deploy only when changes are pushed to the main branch

deploy4:
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh-client

    - sshpass -p $PICAM4_PW scp -o StrictHostKeyChecking=no -r ./* $PICAM4_IP:$DEPLOY_PATH
    - sshpass -p $PICAM4_PW ssh -o StrictHostKeyChecking=no $PICAM4_IP "sudo systemctl restart picam2-streaming.service"

  only:
    - main  # Deploy only when changes are pushed to the main branch

deploy5:
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh-client

    - sshpass -p $PICAM51_PW scp -o StrictHostKeyChecking=no -r ./* $PICAM5_IP:$DEPLOY_PATH
    - sshpass -p $PICAM5_PW ssh -o StrictHostKeyChecking=no $PICAM5_IP "sudo systemctl restart picam2-streaming.service"

  only:
    - main  # Deploy only when changes are pushed to the main branch

deploy6:
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh-client

    - sshpass -p $PICAM6_PW scp -o StrictHostKeyChecking=no -r ./* $PICAM6_IP:$DEPLOY_PATH
    - sshpass -p $PICAM6_PW ssh -o StrictHostKeyChecking=no $PICAM6_IP "sudo systemctl restart picam2-streaming.service"

  only:
    - main  # Deploy only when changes are pushed to the main branch

deploy7:
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh-client
    # - echo $FILE_SERVICE_IP:$DEPLOY_PATH
    # Deploy to your server
    - sshpass -p $PICAM7_PW scp -o StrictHostKeyChecking=no -r ./* $PICAM7_IP:$DEPLOY_PATH
    - sshpass -p $PICAM7_PW ssh -o StrictHostKeyChecking=no $PICAM7_IP "sudo systemctl restart picam2-streaming.service"

  only:
    - main  # Deploy only when changes are pushed to the main branch

deploy8:
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh-client
    # - echo $FILE_SERVICE_IP:$DEPLOY_PATH
    # Deploy to your server
    - sshpass -p $PICAM8_PW scp -o StrictHostKeyChecking=no -r ./* $PICAM8_IP:$DEPLOY_PATH
    - sshpass -p $PICAM8_PW ssh -o StrictHostKeyChecking=no $PICAM8_IP "sudo systemctl restart picam2-streaming.service"

  only:
    - main  # Deploy only when changes are pushed to the main branch